### ISSUE TITLE
All data sets within data catalog should be processed

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-api#23]
Currently data catalogs aren't supported yet, but when a data catalog (like https://www.openarch.nl/datasets/) is provided the API returns an 202. Unclear what happens at the moment, first dataset within datacatalog is processed?

**Comment by coret** [comment]
Clarification of "what happens": all datasets within the datacatalog were processed and stored, but all datasets were put in a graph named after the first dataset in the datacatalog (in this case https://www.openarch.nl/id/dataset_ade). Each encountered dataset should have been place in its "own" graph. Otherwise when the first dataset is separatly added, the whole datacatalog would be overwritten with just the one dataset.

**Comment by coret** [comment]
When adding a datacatalog the API returns a 202 but the logs shows errors and no graphs appear in the triplestore (no triples added to registrations ether).

The registry-api shows the following:
```
{"level":30,"time":1612212519267,"pid":17,"hostname":"registry-api-xxx-xxx","reqId":5,"req":{"method":"POST","url":"/datasets","hostname":"demo.netwerkdigitaalerfgoed.nl","remoteAddress":"xxx.xxx.xxx.xxx","remotePort":54140},"msg":"incoming request"}
{"level":30,"time":1612212519268,"pid":17,"hostname":"registry-api-xxx-xxx","reqId":5,"msg":"https://www.openarch.nl/datasets/"}
{"level":30,"time":1612212536080,"pid":17,"hostname":"registry-api-xxx-xxx","reqId":5,"res":{"statusCode":202},"responseTime":16811.803956985474,"msg":"request completed"}
HTTP error 401 for URL http://graphdb/repositories/registry/statements?subj=%3Chttps%3A%2F%2Fwww.openarch.nl%2Fdatasets%2F%3E&context=%3Chttps%3A%2F%2Fdemo.netwerkdigitaalerfgoed.nl%2Fregistry%2Fregistrations%3E
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236569)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236570)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236571)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236572)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236573)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236574)
.....
```

**Comment by ddeboer** [comment]
Fixed in 4c4b84905cd475ce150e5f30bfde9f7f15f4fea3.

**Comment by coret** [comment]
Retesting the addition of a datacatalog still shows UnhandledPromiseRejectionWarnings in the log and no data added to triplestore. The 401 error is not present anymore.

```
{"level":30,"time":1612262991545,"pid":18,"hostname":"registry-api-xxx-xxx","reqId":3,"req":{"method":"PUT","url":"/datasets/validate","hostname":"demo.netwerkdigitaalerfgoed.nl","remoteAddress":"xxx.xxx.xxx.xxx","remotePort":47622},"msg":"incoming request"}
{"level":30,"time":1612262991546,"pid":18,"hostname":"registry-api-xxx-xxx","reqId":3,"msg":"https://www.openarch.nl/datasets/"}
{"level":30,"time":1612263013886,"pid":18,"hostname":"registry-api-xxx-xxx","reqId":3,"res":{"statusCode":200},"responseTime":22340.488634109497,"msg":"request completed"}
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78129)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78130)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78131)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78132)
....
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78138)

```

**Comment by ddeboer** [comment]
Did some optimizations on my side, but GraphDB keeps crashing with OOMs.
